### ISSUE TITLE
Doesn't work with Bun

### ISSUE THREAD

**Issue by vaaski** [patmood/pocketbase-typegen#79] opened 2023-09-09 12:25 UTC
**Describe the bug**
After [bun](https://bun.sh) hit v1.0.0 yesterday I was eager to give it a spin, but unfortunately this package doesn't seem to work right out of the box. Not sure what the cause is, but if I find some time I might look into it.

<details>
<summary>error log</summary>

```
bunx pocketbase-typegen --db pb_data/data.db --out plugins/pocketbase-types.ts
node:internal/modules/cjs/loader:995
  const err = new Error(message);
              ^

Error: Cannot find module '/private/tmp/pocketbase-typegen@latest--bunx/node_modules/sqlite3/lib/binding/napi-v6-darwin-unknown-arm64/node_sqlite3.node'
Require stack:
- /private/tmp/pocketbase-typegen@latest--bunx/node_modules/sqlite3/lib/sqlite3-binding.js
- /private/tmp/pocketbase-typegen@latest--bunx/node_modules/sqlite3/lib/sqlite3.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/private/tmp/pocketbase-typegen@latest--bunx/node_modules/sqlite3/lib/sqlite3-binding.js:4:17)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/private/tmp/pocketbase-typegen@latest--bunx/node_modules/sqlite3/lib/sqlite3-binding.js',
    '/private/tmp/pocketbase-typegen@latest--bunx/node_modules/sqlite3/lib/sqlite3.js'
  ]
}

Node.js v18.12.1
error: "pocketbase-typegen" exited with code 1 (SIGHUP)
```

</details>

**Versions**
pocketbase-typegen version: 1.1.13
pocketbase version: 0.18.1

**edit**
probably related to oven-sh/bun#158

**Comment by patmood** [comment] 2023-09-09 22:02
Thanks I’m keen to try bun and get this working.

From the error it looks like the SQLite dependency isn’t supported.

**Comment by vaaski** [comment] 2023-09-10 07:10
Glad to hear you're interested as well!
From what I can tell with my little experience with bun, we could probably just use [the built-in SQLite driver](https://bun.sh/docs/api/sqlite).

**Comment by vaaski** [comment] 2023-09-10 08:54
It was actually rather simple to get running, however I did run into some issues.
- Using the build script in your package.json I ran into an issue with ESM. But since bun can run typescript directly, we could theoretically skip that part. I added [another bin entry](https://github.com/vaaski/pocketbase-typegen/commit/7596dfb36d08876fc19f20b3b5b4969484960fd2#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R8) for now.
	<details>
	<summary>ESM Error</summary>
	
	```
	Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data are supported by the default ESM loader. Received protocol 'bun:'
	    at new NodeError (node:internal/errors:393:5)
	    at throwIfUnsupportedURLScheme (node:internal/modules/esm/resolve:1026:11)
	    at defaultResolve (node:internal/modules/esm/resolve:1106:3)
	    at nextResolve (node:internal/modules/esm/loader:163:28)
	    at ESMLoader.resolve (node:internal/modules/esm/loader:841:30)
	    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
	    at ESMLoader.import (node:internal/modules/esm/loader:525:22)
	    at importModuleDynamically (node:internal/modules/esm/translators:110:35)
	    at importModuleDynamicallyCallback (node:internal/process/esm_loader:35:14)
	    at getCollectionsIsomorphic (file:///Users/o/projects/_contrib/pocketbase-typegen/dist/index.js:15:26) {
	  code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
	}
	```
	
	</details>
- Bun doesn't like to import directly from the package.json, will be an easy fix tho.
	<details>
	<summary>package.json error</summary>
	
	```
	SyntaxError: Import named 'version' not found in module '/Users/o/projects/_contrib/pocketbase-typegen/package.json'.
	      at processTicksAndRejections (:1:2602)
	error: "pocketbase-typegen-bun" exited with code 1 (SIGHUP)
	```
	
	</details>
- By default [bun will respect the `#!/usr/bin/env node` shebang](https://bun.sh/docs/cli/bunx#shebangs) and spin up a node process, which can be disabled using `--bun`. We should probably add the shebang during the build process tho.

I think ideally there shouldn't be multiple binaries separating the two runtimes, but I'm not sure how to work that into your build setup.

**Comment by patmood** [comment] 2023-09-13 04:45
I just tried to reproduce this with bun v1.0.1 and it worked without errors. These all seem like issues that could be fixed on the bun side. Can you try again with the newer version of bun?

I'm also on Mac OSX 12.6.5

**Comment by mattmccray** [comment] 2023-09-23 05:08
It doesn't work for me using bun 1.0.2 on an M2 Mac, OSX v13.5.2

I'm trying to run it as a package.json script

```
bun run --bun typegen
```

And it's throwing:

```
error: Cannot find module "/Users/mattm/Projects/Elucidata/aegis-v4/node_modules/sqlite3/lib/binding/napi-v6-darwin-unknown-arm64/node_sqlite3.node" from "/Users/mattm/Projects/Elucidata/aegis-v4/node_modules/sqlite3/lib/sqlite3-binding.js"
error: script "typegen" exited with code 1 (SIGHUP)
```

**Comment by mattmccray** [comment] 2023-09-23 05:16
Looks like my issue was Mac Silicon-related. Running this got it to work.

```
npm install sqlite3 --build-from-source --target_arch=arm64 --fallback-to-build
```

I'm not sure what the bun version of that command is, though.

**Comment by jakubdonovan** [comment] 2023-10-21 04:24
> I just tried to reproduce this with bun v1.0.1 and it worked without errors. These all seem like issues that could be fixed on the bun side. Can you try again with the newer version of bun?
> 
> I'm also on Mac OSX 12.6.5

I just tried it and i could not get it to work. Here's what I did:
`bun install pocketbase-typegen`
added env variables to my .env
```
PB_TYPEGEN_URL
PB_TYPEGEN_EMAIL
PB_TYPEGEN_PASSWORD
```
added the following script to my package.json
` "typegen": "pocketbase-typegen --db ./pb_data/data.db"`

and ran `bunx typegen --env`

which yielded
  🔍 Resolving... 
GET https://registry.npmjs.org/typegen/-/typegen-0.2.0.tgz - 404
error: could not determine executable to run for package typegen

**Comment by patmood** [comment] 2023-10-21 04:41
@jakubdonovan `bunx` is for running packages. So you can run `bunx pocketbase-typegen --db ./pb_data/data.db` and that works for me.

The command for running package.json scripts for your case would be `bun run typegen`, since you called the script "typegen"

Whats confusing is that the package entry point does have a node shebang `#!/usr/bin/env node`, so it's supposed to be running it with node anyway.

The reason I couldn't repro earlier is because it only errors when trying to generate with the database option.

**Comment by jakubdonovan** [comment] 2023-10-21 04:44
> @jakubdonovan `bunx` is for running packages. So you can run `bunx pocketbase-typegen --db ./pb_data/data.db`.
> 
> The command for running package.json scripts for your case would be `bun run typegen`, since you called the script "typegen"
> 
> Whats confusing is that the package entry point does have a node shebang `#!/usr/bin/env node`, so it's supposed to be running it with node anyway.
> 
> The reason I couldn't repro earlier is because it only errors when trying to generate with the database option.

bun run typegen resulted in 
$ pocketbase-typegen --db ./pb_data/data.db
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: SQLITE_CANTOPEN: unable to open database file] {
  errno: 14,
  code: 'SQLITE_CANTOPEN'
}

Node.js v20.3.0
error: script "typegen" exited with code 1 (SIGHUP)

**Comment by jakubdonovan** [comment] 2023-10-21 04:50
I was able to get it to work by running 
`npm i sqlite3 --build-from-source --target_arch=arm64 --fallback-to-build`
and
`npx pocketbase-typegen --env`
which generated types as expected, however I don't think it generated the correct types as 
```
export const pb = new PocketBase(URL) as TypedPocketBase
const res = await pb.collection('menus').getFirstListItem('core_menu_id="628"')
```
res is of type any and not MenusResponse and 
![Uploading Screenshot 2023-10-21 at 11.49.59.png…]()

**Comment by jakubdonovan** [comment] 2023-10-21 09:01
> Glad to hear you're interested as well! From what I can tell with my little experience with bun, we could probably just use [the built-in SQLite driver](https://bun.sh/docs/api/sqlite).
> 
> Looks like it might even be possible to use [`bun test`](https://bun.sh/docs/cli/test). There seems to be one function not implemented, but it already runs crazy fast compared to the jest runner (2s vs 100ms).
> 
> bun test output
> Even running each test 100 times is still multiple times faster than jest :D <img alt="image" width="278" src="https://user-images.githubusercontent.com/17879327/266821996-cb4fb011-af9d-42af-8fde-8a585801ccc0.png">

did you manage to get it to run with the built in sqlite?
`bun run typegen`

> $ pocketbase-typegen --db ./pb_data/data.db
> node:internal/modules/cjs/loader:1070
>   const err = new Error(message);
>               ^
> 
> Error: Cannot find module '/Users/jakubdonovan/Documents/code/foodDiscounts-datacenter/node_modules/sqlite3/lib/binding/napi-v6-darwin-unknown-arm64/node_sqlite3.node'
> Require stack:
> - /Users/jakubdonovan/Documents/code/foodDiscounts-datacenter/node_modules/sqlite3/lib/sqlite3-binding.js
> - /Users/jakubdonovan/Documents/code/foodDiscounts-datacenter/node_modules/sqlite3/lib/sqlite3.js
>     at Module._resolveFilename (node:internal/modules/cjs/loader:1070:15)
>     at Module._load (node:internal/modules/cjs/loader:923:27)
>     at Module.require (node:internal/modules/cjs/loader:1137:19)
>     at require (node:internal/modules/helpers:121:18)
>     at Object.<anonymous> (/Users/jakubdonovan/Documents/code/foodDiscounts-datacenter/node_modules/sqlite3/lib/sqlite3-binding.js:4:17)
>     at Module._compile (node:internal/modules/cjs/loader:1255:14)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1309:10)
>     at Module.load (node:internal/modules/cjs/loader:1113:32)
>     at Module._load (node:internal/modules/cjs/loader:960:12)
>     at Module.require (node:internal/modules/cjs/loader:1137:19) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/Users/jakubdonovan/Documents/code/foodDiscounts-datacenter/node_modules/sqlite3/lib/sqlite3-binding.js',
>     '/Users/jakubdonovan/Documents/code/foodDiscounts-datacenter/node_modules/sqlite3/lib/sqlite3.js'
>   ]
> }
> 
> Node.js v20.3.0
> error: script "typegen" exited with code 1 (SIGHUP)

**Comment by patmood** [comment] 2023-10-22 05:14
@jakubdonovan if you are using `as TypedPocketBase` you need to be using PocketBase SDK v0.18.3 or above. If you are using that version, create a new issue with steps to reproduce it.

As mentioned above, bun seems to work after installing the sqlite package for apple silicon. I'm not sure if that is bun related though

```
bunx --bun pocketbase-typegen -d pb_data/data.db
Created typescript definitions at pocketbase-types.ts
```

**Comment by jakubdonovan** [comment] 2023-10-22 15:30
> bunx --bun pocketbase-typegen -d pb_data/data.db

That's right, looks like I was on an older version of pocketbase. As for sqlite, how'd you install the apple silicon compatible version?
I saw another user install it with `npm install sqlite3 --build-from-source --target_arch=arm64 --fallback-to-build` however using this command with bun instead of npm failed.

**Comment by babakfp** [comment] 2024-05-30 09:04
I'm using bun v1.1.8 on Windows and runing `bun pocketbase-typegen --env -o src/lib/utilities/pb/types-auto-generated.ts` works fine.

**Closed** 2024-11-14 09:54 UTC
